### PR TITLE
linked missing frameworks in Xcode project

### PR DESCRIPTION
**Pull request by aferditamuriqi**

### CODE REVIEW

**Comment by mickael-menu** [comment]
@aferditamuriqi Why did you need to add CryptoSwift to the pbxproj? The other libs declared in the `Cartfile` are not part of the pbxproj.

**Comment by aferditamuriqi** [comment]
I've needed to use carthage submodules in a current project https://github.com/Carthage/Carthage#using-submodules-for-dependencies. and the carthage dependencies in needed to be linked  in the pbxproj. i basically linked all the ones that showed up as missing, it makes sense to have the dependencies linked in the project if those are used in carthage. 
not sure why some are not linked, i can double check and add if missing.

**Comment by mickael-menu** [comment]
@aferditamuriqi Sounds good, yes then maybe we can merge after adding the other dependencies as well.

**Comment by aferditamuriqi** [comment]
I'll make sure to update it this week.

**Comment by mickael-menu** [comment]
@aferditamuriqi I'll merge this one for now, you can open another PR for the missing dependencies

**Pull request merged**
