### PR TITLE
Support subtitle

### PR DESCRIPTION
**Pull request by iaomw**
Adding support for subtitle, also change some function logic to use TitleType enum for reuse.

### CODE REVIEW

**Comment by llemeurfr** [comment]
The change seems ok, but the name `DCMESTitleType`doesn't fit the reality: as per http://www.idpf.org/epub/301/spec/epub-publications.html, title-type definition, the list of type values that a reading system should recognize is defined by EPUB, not DCMES (Dublin Core). 
Therefore pls rename it `EPUBTitleType`.

**Comment by iaomw** [comment]
Thanks, please check.

**Comment by llemeurfr** [comment]
Looking in more details at the code it seems it makes the job; but I don't write Swift, therefore I can't really tell. 

The following is a set of notes, for unit testing.

Let's take a very simple case (from the EPUB spec): 
````
<dc:title>Norwegian Wood</dc:title>
````
Here I have a title, and no subtitle.
Now let's take a more complex case (again from the EPUB spec): 
```
<dc:title id="t1">The Red and the Black</dc:title>
<meta refines="#t1" property="title-type">main</meta>
<dc:title id="t2">A Chronicle of the Nineteenth Century</dc:title>
<meta refines="#t2" property="title-type">subtitle</meta>
```
Here I have a (main) title and a subtitle. I know what the title is because of the id="t1" corresponds to refines="#t1" and property="title-type". Same for the subtitle.

Note: line 332 it is said "returns the _main_ title XML element": this is not true.

What does not seem perfectly handled in the new code is multiple subtitles, with a specific order, like in:
```
 <dc:title id="t1">The Red and the Black</dc:title>
 <meta refines="#t1" property="title-type">main</meta>
 <meta refines="#t1" property="display-seq">1</meta>
    
 <dc:title id="t2">A Chronicle of the Nineteenth Century</dc:title>
 <meta refines="#t2" property="title-type">subtitle</meta>
 <meta refines="#t2" property="display-seq">2</meta>
    
 <dc:title id="t3">A Chronicle of 1830</dc:title>
 <meta refines="#t3" property="title-type">subtitle</meta>
 <meta refines="#t3" property="display-seq">3</meta>
```

In such a case, does` getTitleElement` return a list? ordered?
What is they are several subtitles in different languages? (I agree this would certainly be a mess, but can we have it cleanly processed, e.g get all subtitles in a certain language?

**Comment by iaomw** [comment]
Sorry, forgot to change comment line 332.
I didn't notice it could have multi subtitles, strange. But it's not difficult adding support for it.

As your question, the problem came from multi-lang. I think there are 3 cases:

- All the subtitles have the same lang or no lang. It could simply treated as a list of subtitles.

- All the subtitles have different lang, so logically they are representing the same subtitle. They will become one subtitle as the result. The one who has the same lang as dc:language will be the major one, others will be in the multi-lang dict.

- I am not sure whether that's still valid as software generated ePUB file. There are more than one lang, and for some lang there are more than one subtitle. It's logically not possible to tell who is the translation of who. If the author is not crazy, they shoudl still mean the same thing. So the structure of multi-lang dict will be [lang: [String]], the value for each lang will be an array. How to use it depends on the developer. And the major subtitle will also be replaced by an array.

I can do it, but it's also important to know the real use case. I think most author is making epub by software. Which kind of software or service are they using?

**Comment by iaomw** [comment]
Hi, here is my proposal for the parsing result for any title element and actual type for subtitle.
As the benefits of Swift enum associated values, it's very flexable but still very generic. 

Probably, I should put them in shared models. Please evaluate the possibility.

```
public class MultilangStringList {
    /// Contains the main denomination.
    public let singleString: String?
    /// Contains the alternatives denominations and keyed by language codes, if any.
    public let multiString: [String: [String]]
    
    public init(singleString: String? = nil, multiString: [String: [String]]? = nil,) {
}

public enum TitleParsingResult { // Change the name later
    case singleString(String)
    case singleStringList([String])
    case multilangString(MultilangString)
    case multilangStringList(MultilangStringList)
}
```

**Comment by danielweck** [comment]
Shouldn't Pull Requests target the `develop` branch (not `master`)?

**Comment by aferditamuriqi** [comment]
@danielweck yes it actually should, I am going to change the target, I was going to do that when I get to review and test this PR

**Pull request merged**
